spring:
  application:
    name: microservice-server

server:
  port: 8001

security:
  basic:
    enabled: true
  user:
    name: jiangbin
    password: 10

eureka:
  instance:
    hostname: localhost1
  client:
    #register-with-eureka: true
    #fetch-registry: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://${security.user.name}:${security.user.password}@localhost2:8002/eureka/